In [1]:
article = []

In [2]:
article.append({'text':'I saw the saw.', 'category':'story'})
article.append({'text':'I saw her standing there.', 'category':'story'})
article.append({'text':'Ofcourse I give her an umbrella.', 'category':'story'})
article.append({'text':'But she give me the saw.', 'category':'story'})
article.append({'text':'I come but she run.', 'category':'story'})

article.append({'text':'The moon is Earth’s closest neighbor.', 'category':'science'})
article.append({'text':'It is the brightest object in the night sky..', 'category':'science'})
article.append({'text':'Learn more about the moon.', 'category':'science'})
article.append({'text':'Scientists have studied the moon for thousands of years.', 'category':'science'})
article.append({'text':'The moon is about 4½ billion years old.', 'category':'science'})

article.append({'text':'People build homes.','category':'animal'})
article.append({'text':'A home keeps us warm and dry.', 'category': 'animal'})
article.append({'text':'It gives us a place to live.','category':'animal'})
article.append({'text':'Animals also build homes.','category':'animal'})
article.append({'text':'Read on to see how.','category':'animal'})

article.append({'text':'This is a human skeleton.','category':'health'})
article.append({'text':'It is made of bones.','category':'health'})
article.append({'text':'Bones shape and support your body.','category':'health'})
article.append({'text':'They also protect your organs.','category':'health'})
article.append({'text':'Calcium helps bones grow strong.','category':'health'})

In [3]:
article

[{'text': 'I saw the saw.', 'category': 'story'},
 {'text': 'I saw her standing there.', 'category': 'story'},
 {'text': 'Ofcourse I give her an umbrella.', 'category': 'story'},
 {'text': 'But she give me the saw.', 'category': 'story'},
 {'text': 'I come but she run.', 'category': 'story'},
 {'text': 'The moon is Earth’s closest neighbor.', 'category': 'science'},
 {'text': 'It is the brightest object in the night sky..',
  'category': 'science'},
 {'text': 'Learn more about the moon.', 'category': 'science'},
 {'text': 'Scientists have studied the moon for thousands of years.',
  'category': 'science'},
 {'text': 'The moon is about 4½ billion years old.', 'category': 'science'},
 {'text': 'People build homes.', 'category': 'animal'},
 {'text': 'A home keeps us warm and dry.', 'category': 'animal'},
 {'text': 'It gives us a place to live.', 'category': 'animal'},
 {'text': 'Animals also build homes.', 'category': 'animal'},
 {'text': 'Read on to see how.', 'category': 'animal'},
 {'t

In [4]:
import pandas as pd

In [5]:
news_list = pd.DataFrame.from_dict(article)

In [6]:
news_list

category                                               text
0     story                                     I saw the saw.
1     story                          I saw her standing there.
2     story                   Ofcourse I give her an umbrella.
3     story                           But she give me the saw.
4     story                                I come but she run.
5   science              The moon is Earth’s closest neighbor.
6   science      It is the brightest object in the night sky..
7   science                         Learn more about the moon.
8   science  Scientists have studied the moon for thousands...
9   science            The moon is about 4½ billion years old.
10   animal                                People build homes.
11   animal                      A home keeps us warm and dry.
12   animal                       It gives us a place to live.
13   animal                          Animals also build homes.
14   animal                                Read on to see how.
15   health                          This is a human skeleton.
16   health                               It is made of bones.
17   health                 Bones shape and support your body.
18   health                     They also protect your organs.
19   health                   Calcium helps bones grow strong.

In [7]:
news_list.category.value_counts()

science    5
story      5
animal     5
health     5
Name: category, dtype: int64

In [8]:
# convert label to a numerical variable
news_list['label_num'] = news_list.category.map({'story':0, 'science':1, 'animal':2, 'health':3})

In [9]:
news_list

category                                               text  label_num
0     story                                     I saw the saw.          0
1     story                          I saw her standing there.          0
2     story                   Ofcourse I give her an umbrella.          0
3     story                           But she give me the saw.          0
4     story                                I come but she run.          0
5   science              The moon is Earth’s closest neighbor.          1
6   science      It is the brightest object in the night sky..          1
7   science                         Learn more about the moon.          1
8   science  Scientists have studied the moon for thousands...          1
9   science            The moon is about 4½ billion years old.          1
10   animal                                People build homes.          2
11   animal                      A home keeps us warm and dry.          2
12   animal                       It gives us a place to live.          2
13   animal                          Animals also build homes.          2
14   animal                                Read on to see how.          2
15   health                          This is a human skeleton.          3
16   health                               It is made of bones.          3
17   health                 Bones shape and support your body.          3
18   health                     They also protect your organs.          3
19   health                   Calcium helps bones grow strong.          3

In [10]:
# split X and y into training and testing sets
from sklearn.cross_validation import train_test_split

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [11]:
X = news_list.text
y = news_list.label_num
print(X.shape)
print(y.shape)

(20,)
(20,)


In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(18,)
(2,)
(18,)
(2,)


### Feature Extraction

In [14]:
from sklearn.feature_extraction.text import CountVectorizer

# instantiate the vectorizer
vect = CountVectorizer()

In [15]:
X_train

3                              But she give me the saw.
13                            Animals also build homes.
8     Scientists have studied the moon for thousands...
14                                  Read on to see how.
4                                   I come but she run.
11                        A home keeps us warm and dry.
10                                  People build homes.
15                            This is a human skeleton.
19                     Calcium helps bones grow strong.
18                       They also protect your organs.
17                   Bones shape and support your body.
1                             I saw her standing there.
16                                 It is made of bones.
9               The moon is about 4½ billion years old.
0                                        I saw the saw.
2                      Ofcourse I give her an umbrella.
12                         It gives us a place to live.
6         It is the brightest object in the nigh

In [16]:
X_test

7               Learn more about the moon.
5    The moon is Earth’s closest neighbor.
Name: text, dtype: object

In [17]:
y_train

3     0
13    2
8     1
14    2
4     0
11    2
10    2
15    3
19    3
18    3
17    3
1     0
16    3
9     1
0     0
2     0
12    2
6     1
Name: label_num, dtype: int64

In [18]:
# learn training data vocabulary, then use it to create a document-term matrix
vect.fit(X_train)
X_train_dtm = vect.transform(X_train)

# or

# equivalently: combine fit and transform into a single step
# X_train_dtm = vect.fit_transform(X_train)

In [19]:
X_train_dtm

<18x68 sparse matrix of type '<class 'numpy.int64'>'
	with 95 stored elements in Compressed Sparse Row format>

In [20]:
X_train_dtm

<18x68 sparse matrix of type '<class 'numpy.int64'>'
	with 95 stored elements in Compressed Sparse Row format>

In [21]:
# transform testing data (using fitted vocabulary) into a document-term matrix
X_test_dtm = vect.transform(X_test)
# X_test_dtm

In [22]:
X_train_dtm

<18x68 sparse matrix of type '<class 'numpy.int64'>'
	with 95 stored elements in Compressed Sparse Row format>

## Classification using NaiveBayes

In [23]:
# import and instantiate a Multinomial Naive Bayes model
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [24]:
# train the model using X_train_dtm (timing it with an IPython "magic command")
%time nb.fit(X_train_dtm, y_train)

Wall time: 1.95 ms


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [25]:

# make class predictions for X_test_dtm
y_pred_class = nb.predict(X_test_dtm)

In [26]:
y_pred_class

array([1, 1], dtype=int64)

In [27]:
X_test

7               Learn more about the moon.
5    The moon is Earth’s closest neighbor.
Name: text, dtype: object

In [28]:
# calculate accuracy of class predictions
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

1.0

In [29]:
y_test

7    1
5    1
Name: label_num, dtype: int64

In [30]:
y_pred_class

array([1, 1], dtype=int64)

In [31]:
# print the confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)

array([[2]], dtype=int64)

### Clasification test

In [32]:
new_article = ['I saw cats']
new_article_vect = vect.transform(new_article)
nb.predict(new_article_vect)

array([0], dtype=int64)

### Standarize

In [33]:
from sklearn.preprocessing import StandardScaler  
scaler = StandardScaler(with_mean = False)  
scaler.fit(X_train_dtm)

X_training_vector = scaler.transform(X_train_dtm)  
X_test_vector = scaler.transform(X_test_dtm)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


### Classification using SVM

In [34]:
from sklearn import svm
from sklearn.metrics import accuracy_score
clf = svm.SVC(kernel='linear')
print("Training Classifier...")
%time clf.fit(X_training_vector, y_train)
print("Predicting...")
prediction = clf.predict(X_test_vector)
print("Prediction:",prediction)
accuracy = accuracy_score(y_test, prediction)
# metrics.accuracy_score(y_test, y_pred_class)
print('Accuracy:', accuracy)

Training Classifier...
Wall time: 944 µs
Predicting...
Prediction: [0 0]
Accuracy: 0.0


In [35]:
metrics.accuracy_score(y_test, prediction)

0.0

In [36]:
# print(y_test)
print(prediction)

[0 0]


In [37]:
new_article = ['saw your saw i']
new_article_vect = vect.transform(new_article)
clf.predict(new_article_vect)

# {'news':0, 'finance':1, 'hot':2, 'sport':3, 'travel':4}

array([0], dtype=int64)

In [38]:
vect.get_feature_names()

['4½',
 'about',
 'also',
 'an',
 'and',
 'animals',
 'billion',
 'body',
 'bones',
 'brightest',
 'build',
 'but',
 'calcium',
 'come',
 'dry',
 'for',
 'give',
 'gives',
 'grow',
 'have',
 'helps',
 'her',
 'home',
 'homes',
 'how',
 'human',
 'in',
 'is',
 'it',
 'keeps',
 'live',
 'made',
 'me',
 'moon',
 'night',
 'object',
 'of',
 'ofcourse',
 'old',
 'on',
 'organs',
 'people',
 'place',
 'protect',
 'read',
 'run',
 'saw',
 'scientists',
 'see',
 'shape',
 'she',
 'skeleton',
 'sky',
 'standing',
 'strong',
 'studied',
 'support',
 'the',
 'there',
 'they',
 'this',
 'thousands',
 'to',
 'umbrella',
 'us',
 'warm',
 'years',
 'your']